fieldLayouts:
  ff15c3dd-02a7-49f2-abc7-d45a21bcfe42:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd570735-28dd-428a-8ec7-5dc754b4c447
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 088e6a73-2195-486c-9dc0-ab9a89b93978
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 79d9b187-d156-4a2f-9f2a-4eed22d993d2 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
