color: null
description: null
fieldLayouts:
  c8b7706a-8b66-4428-9de5-542dbe3576dc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-19T03:16:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d29a5c62-ef28-442e-8645-52fa8e4f339d # Youtube ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a216391-2288-47f3-8d0b-ac480ab9c48d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f0f4f6d-a97c-4ee4-b619-1615e23fa587
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-19T03:16:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4690f64a-2eac-4599-abd5-b90d858ba2e2 # Schedule
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6b98bc5-e17d-4d05-96d7-b8791e7aac1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-19T03:16:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bdebca56-d65d-4de4-acaf-ce31343d0035 # Sermon Notes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a25b1948-ae37-4168-a757-79f038779c23
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-19T03:16:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3ecaa8ed-af49-4c58-bb01-da9cfe44eeaf # Bible
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d62abe2-bee5-4b0f-845b-5dd73265033a
            userCondition: null
            warning: null
            width: 100
        name: 'Tabbed Content'
        uid: 55313f1d-e93f-40f6-a6f6-b8d739e81821
        userCondition: null
handle: live
hasTitleField: false
icon: null
name: Live
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
