columnSuffix: qrrsboih
contentColumnType: string(255)
handle: bible
instructions: null
name: Bible
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
