columnSuffix: null
handle: schedule
instructions: null
name: Schedule
searchable: false
settings:
  showTime: 1
  timeloopRequired: true
translationKeyFormat: null
translationMethod: none
type: craftpulse\timeloop\fields\TimeloopField
