columnSuffix: null
contentColumnType: string
fieldGroup: 09e415e9-8220-4857-8370-68e7b9f632a2 # Live
handle: schedule
instructions: null
name: Schedule
searchable: false
settings:
  allowSelfRelations: true
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: Solspace\Calendar\FieldTypes\EventFieldType
