defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  97513086-c063-4780-bd7b-a0eaf8cf2029: # JayGreentree
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
