defaultPlacement: end
enableVersioning: true
handle: live
name: Live
propagationMethod: all
siteSettings:
  97513086-c063-4780-bd7b-a0eaf8cf2029: # JayGreentree
    enabledByDefault: true
    hasUrls: true
    template: live/index.twig
    uriFormat: live
type: single
