defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ea2c62e6-8dc1-43ba-a24e-a6c3abab64e2 # Default
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  97513086-c063-4780-bd7b-a0eaf8cf2029: # JayGreentree
    enabledByDefault: true
    hasUrls: true
    template: _singles/about.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: f26f1807-604c-4aab-a1a1-532b6c3c2f86
type: structure
